export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const INIT_INGREDIENTS_ERROR = 'INIT_INGREDIENTS_ERRORERROR';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILURE = 'PURCHASE_BURGER_FAILURE';